---
title: "Data"
date: "4/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, we provide the download links of estimated tumor-specific total RNA expression proportion ($\pi$), TmS, and intrinsic signature genes for each cancer type from TCGA, EOPC, METABRIC and TRACERx cohorts, as described in our paper [1].

The links in the **TmS summary** column provide text files named ``TmS summary.csv``; each file includes the following columns for the corresponding cancer type:
- Sample ID
- $\pi$ estimate: estimated tumor-specific total RNA expression proportion
- (1-$\rho$)/($\rho$*$\psi$): for TCGA, this is derived by consensus $TmS / [2\pi/(1-\pi)]$. See [Tutorial page](TmS.html) for details about **Consensus TmS estimation**
- TmS

The links in the **Intrinsic tumor signature genes** column provide text files named ``Intrinsic_signature_genes.txt``; each includes the signature genes that are ranked by the gene selection scores for the corresponding cancer type [2, 3]. 

<table>
    <thead>
        <tr>
            <th>Cohort</th>
            <th>Cancer type</th>
            <th>TmS summary</th>
            <th>Intrinsic tumor signature genes</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=15>TCGA</td>
            <td >BLCA</td>
            <td><a href="./etc/TmS/TCGA/BLCA/BLCA_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/BLCA/BLCA_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >BRCA</td>
            <td><a href="./etc/TmS/TCGA/BRCA/BRCA_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/BRCA/BRCA_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >CRC</td>
            <td><a href="./etc/TmS/TCGA/CRC/CRC_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/CRC/CRC_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >HNSC</td>
            <td><a href="./etc/TmS/TCGA/HNSC/HNSC_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/HNSC/HNSC_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >KICH</td>
            <td><a href="./etc/TmS/TCGA/KICH/KICH_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/KICH/KICH_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >KIRC</td>
            <td><a href="./etc/TmS/TCGA/KIRC/KIRC_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/KIRC/KIRC_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >KIRP</td>
            <td><a href="./etc/TmS/TCGA/KIRP/KIRP_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/KIRP/KIRP_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >LIHC</td>
            <td><a href="./etc/TmS/TCGA/LIHC/LIHC_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/LIHC/LIHC_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >LUAD</td>
            <td><a href="./etc/TmS/TCGA/LUAD/LUAD_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/LUAD/LUAD_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >LUSC</td>
            <td><a href="./etc/TmS/TCGA/LUSC/LUSC_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/LUSC/LUSC_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >PAAD</td>
            <td><a href="./etc/TmS/TCGA/PAAD/PAAD_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/PAAD/PAAD_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >PRAD</td>
            <td><a href="./etc/TmS/TCGA/PRAD/PRAD_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/PRAD/PRAD_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >STAD</td>
            <td><a href="./etc/TmS/TCGA/STAD/STAD_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/STAD/STAD_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >THCA</td>
            <td><a href="./etc/TmS/TCGA/THCA/THCA_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/THCA/THCA_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >UCEC</td>
            <td><a href="./etc/TmS/TCGA/UCEC/UCEC_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TCGA/UCEC/UCEC_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>

        <tr>
            <td >EOPC</td>
            <td ></td>
            <td><a href="./etc/TmS/EOPC/EOPC_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/EOPC/EOPC_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>

        <tr>
            <td >METABRIC</td>
            <td ></td>
            <td><a href="./etc/TmS/METABRIC/METABRIC_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/METABRIC/METABRIC_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>
        <tr>
            <td >TRACERx</td>
            <td ></td>
            <td><a href="./etc/TmS/TRACERx/TRACERx_TmS_summary.csv">link</a></td>
            <td><a href="./etc/TmS/TRACERx/TRACERx_Intrinsic_signature_genes.txt">link</a> </td>
        </tr>

    </tbody>
</table>

**Note**: EOPC, Early-Onset Prostate Cancer [4]; METABRIC, Molecular Taxonomy of Breast Cancer International Consortium [5]; TRACERx, Tracking Cancer Evolution through therapy [6]. 


## Reference

[1] Cao, S. et al. Estimation of tumor cell total mRNA expression in 15 cancer types predicts disease progression. Nat Biotechnol (2022). https://doi.org/10.1038/s41587-022-01342-x.

[2] Ahn, J. et al. DeMix: Deconvolution for mixed cancer transcriptomes using raw measured data. Bioinformatics 29, 1865–1871 (2013).

[3] Wang, Z. et al. Transcriptome Deconvolution of Heterogeneous Tumor Samples with Immune Infiltration. iScience 9, 451–460 (2018).

[4] Gerhauser, C. et al. Molecular Evolution of Early-Onset Prostate Cancer Identifies Molecular Risk Markers and Clinical Trajectories. Cancer Cell 34, 996–1011 (2018).

[5] Curtis, C. et al. The genomic and transcriptomic architecture of 2,000 breast tumours reveals novel subgroups. Nature 486, 346–352 (2012).

[6] Jamal-Hanjani, M. et al. Tracking the evolution of non-small-cell lung cancer. N. Engl. J. Med. 376, 2109–2121 (2017).
